[package]
name = "shared_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
chrono = "0.4.38"
mongodb = {version = "3.0.1" }
redis = { version = "0.25.4", features = ["tokio-comp","aio","connection-manager"] }